### ISSUE TITLE
wow, I didn't see this!

### ISSUE THREAD

**Issue by jonschlinkert** [tunnckoCore/add-lazy-cache#1]
man I just saw that you created this! I created lazy-cache-cli after you created this, but they both do something similar. sorry, I wish I had seen this first

**Comment by tunnckoCore** [comment]
Yea, that was the idea. And intentionally i did not get `lazy-cache-cli` cuz i dont have the time atm.

Good thing would be to add option to `lazy-cache-cli` for different template, cuz we standard-style-guys dont use semicolons, lol, you know. :D 
It's not so big problem to just run `standard --format` over created `utils.js` but yea..

**Comment by jonschlinkert** [comment]
> we standard-style-guys dont use semicolons, lol, you know. :D

yeah good idea, I don't like anything about standard style :)

**Comment by tunnckoCore** [comment]
I even thought for `lazy-cache-template`, idk.
